In [3]:
import pandas as pd

# Load the Excel files
df1 = pd.read_excel('rekap.xlsx', sheet_name='Data')
df2 = pd.read_excel('prak1.xlsx', sheet_name='Form Responses 1')

# Merge the dataframes on the 'NPM' column
merged_df = pd.merge(df1, df2, on='NPM', how='inner')

# Save the merged dataframe to a new Excel file
merged_df.to_excel('merged_file.xlsx', index=False)

   Unnamed: 0              Unnamed: 1                  Unnamed: 2 Unnamed: 3  \
0         NaN                     NaN                         NaN        NaN
1          No                     NPM                        Nama   Kelompok
2         NaN                     NaN                         NaN        NaN
3           1           2108107010051  MUHAMMAD ALMER ZUHDI RANGK          7
4           2           2208107010001           AULIA VIKA RAHMAN          4
5           3           2208107010003                 ALVIA ZUHRA          8
6           4           2208107010005                 MEUTIA AINI          3
7           5           2208107010007               SADINAL MUFTI          6
8           6           2208107010009      IFFATUN NISA NASRULLAH          3
9           7           2208107010011            M. NABIL MAULANA          5
10          8           2208107010013        MUHAMMAD HABIL ASWAD          2
11          9           2208107010015           SHOFIA NURUL HUDA          4
12         10           2208107010017       AKHSANIA MAISA RAHMAH          3
13         11           2208107010019                   ADE RISKI          9
14         12           2208107010021             MUHAMMAD RAIHAN          1
15         13           2208107010023  MUHAMMAD BINTANG INDRA HID          1
16         14           2208107010025                 AGIL MUGHNI          4
17         15           2208107010027                CUT DAHLIANA          7
18         16           2208107010029     M. IHSAN RIZQULLAH ADFA          2
19         17           2208107010031              AMMAR QURTHUBY          9
20         18           2208107010033         AHMAD SYAH RAMADHAN          6
21         19           2208107010037       WILLY JONATHAN ARSYAD         12
22         20           2208107010039              QANDILA AHMARA          8
23         21           2208107010041             DELLA RAHMATIKA          9
24         22           2208107010043                 NAUFAL AQIL         11
25         23           2208107010045       M. SYAHIDAL AKBAR ZAS          2
26         24           2208107010047              M. TARIS RIZKI          1
27         25           2208107010049          NASHED BAYAZID ALI         10
28         26           2208107010059       FIRJATULLAH AFNY ABUS          2
29         27           2208107010061                ZUWI PERTIWI         10
30         28           2208107010063           HIDAYAT NUR HAKIM          5
31         29           2208107010065               SISKA AULIANI          9
32         30           2208107010067                ARIF MAULANA          5
33         31           2208107010068              NOVIA ANGREINI         11
34         32           2208107010069              AZIMAH AL-HUDA          8
35         33           2208107010071       FATHIYA NAMIRA FARDHI          5
36         34           2208107010072                 GLENN HAKIM          8
37         35           2208107010073           AZRON AZMUZAHRI T          7
38         36           2208107010075       MUHAMMAD NOUVAL RIFQI          1
39         37           2208107010078              IWANI KHAIRINA         12
40         38           2208107010079              AZZARIYAT AZRA         10
41         39           2208107010081              DINDA MAHARANI          6
42         40           2208107010083       CUT MARDILLA AGUSTINE         11
43         41           2208107010084               RAIHAN FIRYAL          3
44         43           2208107010089              MUHAMMAD ALVIN         12
45         44           2208001010005               Dewina Alayda          7
46         45           2208001010013        Chairul Huda Lestari          4
47        NaN                     NaN                         NaN        NaN
48        NaN                     NaN                         NaN        NaN
49        NaN                     NaN                         NaN        NaN
50        NaN  Pindah Kelas Ke Tekkom                         NaN        NaN

   Unnamed: 4  Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  \
0         NaN         NaN         NaN         NaN         NaN         NaN
1    TES AWAL         NaN         NaN         NaN         NaN         NaN
2           1         2.0         3.0         4.0         5.0         6.0
3         NaN         NaN         NaN         NaN         NaN         NaN
4         NaN         NaN         NaN         NaN         NaN         NaN
5         NaN         NaN         NaN         NaN         NaN         NaN
6         NaN         NaN         NaN         NaN         NaN         NaN
7         NaN         NaN         NaN         NaN         NaN         NaN
8         NaN         NaN         NaN         NaN         NaN         NaN
9         NaN         NaN         NaN         NaN         NaN         NaN
10        NaN         NaN         NaN         NaN         NaN         NaN
11        NaN         NaN         NaN         NaN         NaN         NaN
12        NaN         NaN         NaN         NaN         NaN         NaN
13        NaN         NaN         NaN         NaN         NaN         NaN
14        NaN         NaN         NaN         NaN         NaN         NaN
15        NaN         NaN         NaN         NaN         NaN         NaN
16        NaN         NaN         NaN         NaN         NaN         NaN
17        NaN         NaN         NaN         NaN         NaN         NaN
18        NaN         NaN         NaN         NaN         NaN         NaN
19        NaN         NaN         NaN         NaN         NaN         NaN
20        NaN         NaN         NaN         NaN         NaN         NaN
21        NaN         NaN         NaN         NaN         NaN         NaN
22        NaN         NaN         NaN         NaN         NaN         NaN
23        NaN         NaN         NaN         NaN         NaN         NaN
24        NaN         NaN         NaN         NaN         NaN         NaN
25        NaN         NaN         NaN         NaN         NaN         NaN
26        NaN         NaN         NaN         NaN         NaN         NaN
27        NaN         NaN         NaN         NaN         NaN         NaN
28        NaN         NaN         NaN         NaN         NaN         NaN
29        NaN         NaN         NaN         NaN         NaN         NaN
30        NaN         NaN         NaN         NaN         NaN         NaN
31        NaN         NaN         NaN         NaN         NaN         NaN
32        NaN         NaN         NaN         NaN         NaN         NaN
33        NaN         NaN         NaN         NaN         NaN         NaN
34        NaN         NaN         NaN         NaN         NaN         NaN
35        NaN         NaN         NaN         NaN         NaN         NaN
36        NaN         NaN         NaN         NaN         NaN         NaN
37        NaN         NaN         NaN         NaN         NaN         NaN
38        NaN         NaN         NaN         NaN         NaN         NaN
39        NaN         NaN         NaN         NaN         NaN         NaN
40        NaN         NaN         NaN         NaN         NaN         NaN
41        NaN         NaN         NaN         NaN         NaN         NaN
42        NaN         NaN         NaN         NaN         NaN         NaN
43        NaN         NaN         NaN         NaN         NaN         NaN
44        NaN         NaN         NaN         NaN         NaN         NaN
45        NaN         NaN         NaN         NaN         NaN         NaN
46        NaN         NaN         NaN         NaN         NaN         NaN
47        NaN         NaN         NaN         NaN         NaN         NaN
48        NaN         NaN         NaN         NaN         NaN         NaN
49        NaN         NaN         NaN         NaN         NaN         NaN
50        NaN         NaN         NaN         NaN         NaN         NaN

    Unnamed: 10  Unnamed: 11  Unnamed: 12  Unnamed: 13  Unnamed: 14  \
0           NaN          NaN          NaN          NaN          NaN
1           NaN          NaN          NaN          NaN          NaN
2           7.0          8.0          9.0         10.0         11.0
3           NaN          NaN          NaN          NaN          NaN
4           NaN          NaN          NaN          NaN          NaN
5           NaN          NaN          NaN          NaN          NaN
6           NaN          NaN          NaN          NaN          NaN
7           NaN          NaN          NaN          NaN          NaN
8           NaN          NaN          NaN          NaN          NaN
9           NaN          NaN          NaN          NaN          NaN
10          NaN          NaN          NaN          NaN          NaN
11          NaN          NaN          NaN          NaN          NaN
12          NaN          NaN          NaN          NaN          NaN
13          NaN          NaN          NaN          NaN          NaN
14          NaN          NaN          NaN          NaN          NaN
15          NaN          NaN          NaN          NaN          NaN
16          NaN          NaN          NaN          NaN          NaN
17          NaN          NaN          NaN          NaN          NaN
18          NaN          NaN          NaN          NaN          NaN
19          NaN          NaN          NaN          NaN          NaN
20          NaN          NaN          NaN          NaN          NaN
21          NaN          NaN          NaN          NaN          NaN
22          NaN          NaN          NaN          NaN          NaN
23          NaN          NaN          NaN          NaN          NaN
24          NaN          NaN          NaN          NaN          NaN
25          NaN          NaN          NaN          NaN          NaN
26          NaN          NaN          NaN          NaN          NaN
27          NaN          NaN          NaN          NaN          NaN
28          NaN          NaN          NaN          NaN          NaN
29          NaN          NaN          NaN          NaN          NaN
30          NaN          NaN          NaN          NaN          NaN
31          NaN          NaN          NaN          NaN          NaN
32          NaN          NaN          NaN          NaN          NaN
33          NaN          NaN          NaN          NaN          NaN
34          NaN          NaN          NaN          NaN          NaN
35          NaN          NaN          NaN          NaN          NaN
36          NaN          NaN          NaN          NaN          NaN
37          NaN          NaN          NaN          NaN          NaN
38          NaN          NaN          NaN          NaN          NaN
39          NaN          NaN          NaN          NaN          NaN
40          NaN          NaN          NaN          NaN          NaN
41          NaN          NaN          NaN          NaN          NaN
42          NaN          NaN          NaN          NaN          NaN
43          NaN          NaN          NaN          NaN          NaN
44          NaN          NaN          NaN          NaN          NaN
45          NaN          NaN          NaN          NaN          NaN
46          NaN          NaN          NaN          NaN          NaN
47          NaN          NaN          NaN          NaN          NaN
48          NaN          NaN          NaN          NaN          NaN
49          NaN          NaN          NaN          NaN          NaN
50          NaN          NaN          NaN          NaN          NaN

    Unnamed: 15  Unnamed: 16  Unnamed: 17
0           NaN          NaN          NaN
1           NaN          NaN          NaN
2          12.0         13.0         14.0
3           NaN          NaN          NaN
4           NaN          NaN          NaN
5           NaN          NaN          NaN
6           NaN          NaN          NaN
7           NaN          NaN          NaN
8           NaN          NaN          NaN
9           NaN          NaN          NaN
10          NaN          NaN          NaN
11          NaN          NaN          NaN
12          NaN          NaN          NaN
13          NaN          NaN          NaN
14          NaN          NaN          NaN
15          NaN          NaN          NaN
16          NaN          NaN          NaN
17          NaN          NaN          NaN
18          NaN          NaN          NaN
19          NaN          NaN          NaN
20          NaN          NaN          NaN
21          NaN          NaN          NaN
22          NaN          NaN          NaN
23          NaN          NaN          NaN
24          NaN          NaN          NaN
25          NaN          NaN          NaN
26          NaN          NaN          NaN
27          NaN          NaN          NaN
28          NaN          NaN          NaN
29          NaN          NaN          NaN
30          NaN          NaN          NaN
31          NaN          NaN          NaN
32          NaN          NaN          NaN
33          NaN          NaN          NaN
34          NaN          NaN          NaN
35          NaN          NaN          NaN
36          NaN          NaN          NaN
37          NaN          NaN          NaN
38          NaN          NaN          NaN
39          NaN          NaN          NaN
40          NaN          NaN          NaN
41          NaN          NaN          NaN
42          NaN          NaN          NaN
43          NaN          NaN          NaN
44          NaN          NaN          NaN
45          NaN          NaN          NaN
46          NaN          NaN          NaN
47          NaN          NaN          NaN
48          NaN          NaN          NaN
49          NaN          NaN          NaN
50          NaN          NaN          NaN

In [8]:
print("Columns in df1: ", df1.columns)
print("Columns in df2: ", df2.columns)

Columns in df1:  Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29',
       'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33',
       'Unnamed: 34'],
      dtype='object')
Columns in df2:  Index(['Timestamp', 'NPM', 'Cornell Notes'], dtype='object')

In [14]:
import pandas as pd

# Load the Excel files
df1 = pd.read_excel('rekap.xlsx', sheet_name='Data')
df2 = pd.read_excel('prak2.xlsx', sheet_name='Form Responses 1')

# Keep only the 'NPM' column from df1
df1 = df1[['NPM', 'Nama']]

# Merge the dataframes on the 'NPM' column
merged_df = pd.merge(df1, df2, on='NPM', how='inner')

# Save the merged dataframe to a new Excel file
merged_df.to_excel('Prak2akhir.xlsx', index=False)